#!/bin/bash

echo "Downloading script"
cd /usr/local/bin
wget https://raw.githubusercontent.com/ram4git/scripts/master/emailOnCpuOverLimit
chmod 777 emailOnCpuOverLimit

echo "Setting up cron job"
(crontab -l ; echo "* * * * * ./emailOnCpuOverLimit") | sort - | uniq - | crontab -

echo "Done"
